# ASP.NET Core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.102'

- script: dotnet build --configuration $(buildConfiguration) BlazorAppWASM.sln
  displayName: 'dotnet build $(buildConfiguration) BlazorAppWASM'
- script: dotnet publish --output $(Build.ArtifactStagingDirectory)/BlazorAppWASM.sln
  displayName: 'dotnet publish BlazorAppWASM'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'blazordist'
